// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrtiQIFO3sAHvNQoYbztZoIrs8zzcpPY',
    appId: '1:545637497373:web:6026bdc23cae2d1f8224f4',
    messagingSenderId: '545637497373',
    projectId: 'flutter-digifarm',
    authDomain: 'flutter-digifarm.firebaseapp.com',
    databaseURL: 'https://flutter-digifarm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-digifarm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbS_GkdwInjhqYRD7Jdy5oOWy-BANiSQI',
    appId: '1:545637497373:android:d722ddb4c49fb67b8224f4',
    messagingSenderId: '545637497373',
    projectId: 'flutter-digifarm',
    databaseURL: 'https://flutter-digifarm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-digifarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObbDHZbAj9Nn8YKCqAnjy2C0lOf8keeo',
    appId: '1:545637497373:ios:6afd43ee335212698224f4',
    messagingSenderId: '545637497373',
    projectId: 'flutter-digifarm',
    databaseURL: 'https://flutter-digifarm-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-digifarm.firebasestorage.app',
    iosBundleId: 'com.example.digifarm',
  );
}
